### ISSUE TITLE
Not registering ticks for certain weapons

### ISSUE THREAD

**Issue by LuckyBucky77** [winterdaze/tick-counter#10]
This issue was also mentioned in a post from Aug 22. The plugin fails to register attack ticks from several weapons in game. Some that I've identified:

Sanguinesti Staff (and tridents) (4-tick)
Tentacle whip (and normal whip) (4-tick)

This list is just what I see on a daily basis doing ToB, so there may be others. 

With some testing, other bugged weapons:
Blisterwood flail (5-tick)
Abyssal dagger (4-tick)
Arclight (4-tick)

Troubleshooting attempts:
1. Uninstall and reinstall from Runelite plugin hub.
2. Manually delete the .jar file from the plugins folder for Runelite.

I've spoken with other people who don't seem to have an issue. Maybe there's another plugin that is interfering? 

Any help is appreciated.

**Comment by Richardant** [comment]
added on PR https://github.com/winterdaze/tick-counter/pull/18 thank you
