### ISSUE TITLE
Request for repo transfer

### ISSUE THREAD

**Issue by LlemonDuck** [winterdaze/tick-counter#16]
Hello! A couple days ago I opened PR #15, although I didn't check whether the repository was active first.

I've since noticed a few more weapons and animations that aren't being counted correctly, like the Blazing blowpipe, and the more recent special attack animations for the elder maul and Osmumten's fang. I've updated them locally, but if it is amenable to you, I would like to take over the plugin ownership to keep it up to date more frequently without throwing a million PRs your way. You would, of course, be credited for all the ground work you've done.

If you prefer to retain ownership of the plugin but are open to collaboration, it is also possible to add me as an author in this repository and the plugin hub manifest, which would grant me the ability to release new versions but keeps the plugin under your namespace.

I am on the plugin hub maintainer team, so this can be as simple as just letting me know here, and I can do all the other necessary bookkeeping.

If I don't hear from you in the next couple weeks or so, I will assume the plugin is no longer being maintained and take ownership as well.

Please let me know either way, thanks!

**Comment by winterdaze** [comment]
Hi there, apologies for not being active on keeping things up to date I hardly play osrs anymore apart from a bit on big content releases here and there. Thanks for your offer on helping maintain this, I have added you as a collaborator and am good with you being added to the manifest. Let me know if there's anything else you need after you accept the invite

**Comment by LlemonDuck** [comment]
Thank you! Everything looks good. I'll be rolling out an update now with the noxious halberd and blazing blowpipe, and will continue to push out others as I come across them.
