### ISSUE TITLE
zammy spear really needs to be optional

### ISSUE THREAD

**Issue by hexzie** [winterdaze/tick-counter#6]
So let me start off by saying your tick counter is truly amazing for corp. have been using it a long time and love it. today you updated it and made it so zammy spear is counter and that's super problematic for what corp ffa07 does (corp massing clan chat) we can no longer accurately or easily tell if a person is speccing with dwh or bgs twice. is there any way you could make zammy spear optional on being counted. we heavily rely on your tick counter.  Thanks in advance!

**Comment by Box-Of-Hats** [comment]
Thanks for sorting this so quickly 🎉🎉

**Comment by winterdaze** [comment]
Added config option to exclude zammy spear ticks, with default setting that the ticks are included
